export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const CREATE_INGREDIENT = 'CREATE_INGREDIENT';
export const FETCH_INGREDIENT = 'FETCH_INGREDIENT';
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';
export const UPDATE_INGREDIENT = 'UPDATE_INGREDIENT';